# run parameters
initial_pose_std_xy: 0.2
initial_pose_std_theta: 0.2617
goal_tolerance: 0.4
run_timeout: 7200.0
waypoint_timeout: 600
estimated_pose_error_timeout: 30
ps_snapshot_period: 10.0
write_estimated_poses_period: 0.1
robot_radius: 0.2
random_traversal_path: true
fewer_nav_goals: false
min_distance_traversal_path: 2.0  # if fewer_nav_goals is true, when the distance between two consecutive poses in the traversal path is less than this value, the second pose will be excluded.
environment_type: 'simulation'

# topic names
scan_topic: /scan
scan_gt_topic: /scan_gt
amcl_particles_topic: /particlecloud
estimated_pose_correction_topic: /gmapping_pose
ground_truth_pose_topic: /base_footprint_gt

# service names
save_map_service: /slam_toolbox/save_map
serialize_map_service: /slam_toolbox/serialize_map

# action names
navigate_to_pose_action: /move_base

# frame names
fixed_frame: map
robot_base_frame: base_link_realistic

# gazebo entity names
robot_entity_name: robot
